export enum MODEL_NAMES {
  USER = 'users',
  HOSTEL = 'hostels',
  COUNTER = 'counters',
  GALLERY = 'galleries',
  GALLERY_HOSTEL_LINKS = 'galery_hostel_links',
  GALLERY_ROOM_LINKS = 'gallery_room_links',
  AMENITIES = 'amenities',
  HOSTEL_X_AMENITIES = 'hostel_amenities_links',
  ROOM_X_AMENITIES = 'room_amenities_links',
  BED = 'beds',
  ROOM = 'rooms',
  LOCATION = 'locations',
  CATEGORY = 'categories',
  ROOM_TYPES = 'room_types',
  BOOKING = 'bookings',
  BOOKING_STATUS_HISTORY = 'booking_status_histories',

  INVOICE_ITEMS = 'invoice_items',
  INVOICES = 'invoices',
  CONTRACTS = 'contracts',
  TRANSACTIONS = 'transactions',
  CONTACT_US = 'contact_us',
  COMPLAINTS = 'complaints',
  COMPLAINTS_STATUS_HISTORY = 'complaints_status_histories',
  COMPLAINTS_GALLERY_LINKS = 'complaints_gallery_links',

  DAMAGE_AND_SPLIT = 'damage_and_splits',
  DAMAGE_AND_SPLIT_DETAILS = 'damage_and_split_details',
  PAYMENTS = 'payments',
  INVOICE = 'invoices',
  CHECKOUT_REQUEST = 'checkout_requests',
  LAUNDRY_BOOKING = 'laundry_bookings',
}
